### ISSUE TITLE
[1.20.1] Game crashes when I enter the server

### ISSUE THREAD

**Issue by lays24mc** [Edivad99/EdivadLib#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As soon as I use the latest version of EdivadLib 2.0.1 and OpenElevator is installed with it, I can't join my server anymore. I come to the world and the client crashes. Downgrade I EdivasLib again to 2.0.0 again it works.

### How can I reproduce this bug or crash?

Install newest EdivadLib 2.0.1, OpenElevator 1.8.15 and Forge 47.1.3

### Configuration

```markdown
EdivadLib 2.0.1
OpenBlocks Elevator 1.8.15
Forge 47.1.3
```

### Relevant log output

```shell
Crashlog: https://pastebin.com/98v0J0tS
```

**Comment by Edivad99** [comment]
Sorry but in the crash I don't see any problem caused by EdivadLib.
Can you try loading the world with just EdivadLib and see if it crashes?

**Comment by lays24mc** [comment]
I had reuploaded the crashlog again just now, because I saw that it was a wrong one. So the link should be new. In the last one was something with direwolf in it, that was the wrong one

**Comment by Edivad99** [comment]
`java.lang.NullPointerException: Cannot read field "f_108573_" because "player.f_108618_" is null
	at xyz.vsngamer.elevatorid.ElevatorHandler.onInput(ElevatorHandler.java:31) ~[elevatorid-1.20.1-1.8.15.jar%23462!/:1.20.1-1.8.15] {re:classloading}`
That is the problem

**Comment by Edivad99** [comment]
> Can you try loading the world with just EdivadLib and see if it crashes?

**Comment by lays24mc** [comment]
hmm then not. It is only when both are installed. I had first looked at Openblock Elevator and there is one already open, however, there was also mentioned in the thread that it was there another mod. So I thought I'd post it here too :). So it's more on Openblock Elevator, right?

**Comment by Edivad99** [comment]
Yep

**Comment by lays24mc** [comment]
Okay, then I apologize for the wrong message and will pass it once at OpenBlocks Elevator :)

**Comment by Edivad99** [comment]
Don't worry :)
